Repository JuliaArrays/StaticArrays.jl, pull requests merged in 2019-11, with the labels that each got.

#666 Conversion of SizedArray to Array reshapes
  src/SizedArray.jl
  test/SizedArray.jl
  test/abstractarray.jl
Labels: breaking-change, bugfix, cleanup

#685 Unpirate Union{}[]
  src/initializers.jl
  test/initializers.jl
Labels: bugfix

#688 No longer skip a test which is fixed upstream.
  test/SHermitianCompact.jl
Labels: cleanup

#689 Move concatenation into abstractarray.jl
  src/abstractarray.jl
  src/linalg.jl
  test/abstractarray.jl
  test/linalg.jl
Labels: cleanup

#690 Tidy one() implementation and UniformScaling constructors
  src/MArray.jl
  src/MVector.jl
  src/SArray.jl
  src/SDiagonal.jl
  src/SHermitianCompact.jl
  src/SVector.jl
  src/StaticArrays.jl
  src/abstractarray.jl
  src/det.jl
  src/linalg.jl
  src/qr.jl
  src/util.jl
  test/linalg.jl
  test/testutil.jl
Labels: cleanup
