Repository JuliaArrays/StaticArrays.jl, pull requests merged in 2019-09, with the labels that each got.

#643 Simplify broadcast code generation
  src/broadcast.jl
  test/broadcast.jl
Labels: bugfix, cleanup

#633 WIP/RFC: Implement SA[...] syntax for SArray literals
  src/StaticArrays.jl
  src/initializers.jl
  test/initializers.jl
  test/runtests.jl
Labels: design, enhancement

#657 [WIP] Nested views with static indexing
  src/indexing.jl
  test/indexing.jl
Labels: enhancement

#659 [WIP] faster reductions
  src/mapreduce.jl
Labels: bugfix, performance

#656 SA type aliases for constructors with precise eltype
  README.md
  docs/src/pages/quickstart.md
  src/StaticArrays.jl
  src/initializers.jl
  test/initializers.jl
Labels: design, enhancement

#467 [WIP] README updates for 0.7
  README.md
  perf/README_benchmarks.jl
Labels: documentation

#663 Broadcasting with tuples (fixes #485)
  src/broadcast.jl
  test/broadcast.jl
Labels: bugfix

#664 Avoid eltype degrading to `Union{}` for empty map/broadcast
  src/broadcast.jl
  src/mapreduce.jl
  test/broadcast.jl
  test/linalg.jl
  test/lu.jl
  test/mapreduce.jl
Labels: bugfix

#662 fix for issue #641
  src/mapreduce.jl
  test/mapreduce.jl
  test/runtests.jl
Labels: bugfix, method-ambiguity
