Repository JuliaArrays/StaticArrays.jl, pull requests merged in 2020-09, with the labels that each got.

#823 Avoid type piracy in similar
  src/abstractarray.jl
Labels: cleanup

#783 Sized AbstractArray
  src/MArray.jl
  src/SizedArray.jl
  src/matrix_multiply_add.jl
  test/SizedArray.jl
  test/abstractarray.jl
  test/matrix_multiply_add.jl
Labels: breaking-change, feature

#832 Make setindex! return the array rather than the value
  src/FieldArray.jl
  src/MArray.jl
  src/indexing.jl
  src/util.jl
  test/FieldMatrix.jl
  test/MArray.jl
  test/indexing.jl
Labels: bugfix

#833 Change order of function definition in matrix multiplication code
  src/matrix_multiply.jl
  src/matrix_multiply_add.jl
Labels: bugfix
