Repository JuliaArrays/StaticArrays.jl, pull requests merged in 2020-01, with the labels that each got.

#706 Views of zero-dimensional arrays
  src/indexing.jl
  test/indexing.jl
Labels: bugfix

#709 Fix eltype for recurisve adjoint/transpose
  src/linalg.jl
  test/linalg.jl
Labels: bugfix, linear-algebra

#720 add undef tags to docs for MMatrix and MVector
  src/MMatrix.jl
  src/MVector.jl
Labels: documentation
