Repository JuliaArrays/StaticArrays.jl, pull requests merged in 2020-04, with the labels that each got.

#759 Fix convert(::Type{<:StaticArray}, ::UniformScaling)
  src/linalg.jl
  test/linalg.jl
Labels: bugfix

#762 Ability to select particular test cases
  test/ambiguities.jl
  test/runtests.jl
  test/testutil.jl
Labels: cleanup

#738 Add in-place multiply-add
  Project.toml
  benchmark/bench_matrix_ops.jl
  src/StaticArrays.jl
  src/matrix_multiply.jl
  src/matrix_multiply_add.jl
  test/matrix_multiply_add.jl
  test/runtests.jl
Labels: enhancement, linear-algebra, performance

#763 Fix accidential API breakage in one()
  src/linalg.jl
  test/linalg.jl
Labels: bugfix

#766 Add singularity checks for lu, method for issuccess.
  src/StaticArrays.jl
  src/det.jl
  src/lu.jl
  test/lu.jl
Labels: breaking-change, bugfix, linear-algebra

#769 Remove show(::IO, ::Type{StaticArrays.Blah}) overloads
  src/MMatrix.jl
  src/MVector.jl
  src/SMatrix.jl
  src/SUnitRange.jl
  src/SVector.jl
  src/Scalar.jl
  test/SUnitRange.jl
Labels: bugfix, cleanup
